/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helloJNI */

#ifndef _Included_helloJNI
#define _Included_helloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloJNI
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_helloJNI_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
